name: Deploy from gh-pages

on:
  push:
    branches: [ gh-pages ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: 🚀 Deploy to server
      uses: appleboy/ssh-action@v1.1.0
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        passphrase: ${{ secrets.SSH_PASSPHRASE }}
        port: ${{ secrets.PORT }}
        script: |
          set -e
          echo "🔌 Connexion SSH établie"
          
          echo "📂 Navigation vers le répertoire du projet"
          cd /var/www/html/contact-me
          
          echo "📥 Pull des modifications depuis gh-pages..."
          git pull origin gh-pages
          
          echo "📋 Copie du fichier index.html vers la racine"
          sudo cp index.html ../index.html
          
          echo "✅ Déploiement terminé le $(date)"